[env:esp32-s3-devkitc-1]
platform  = espressif32
board     = esp32-s3-devkitc-1
framework = arduino

; Serial monitor speed
monitor_speed = 115200

; Required libraries
lib_deps =
    bblanchon/ArduinoJson @ ^7.2.0

; Enables the TWAI (CAN) driver built into the ESP-IDF / arduino-esp32 core
; No extra library needed — driver/twai.h is part of the board package.

build_flags =
    -DBOARD_HAS_PSRAM
